= OVS Programming Design
Eric Li <sze.li@futurewei.com>, Xiaodong Zhang <xzhang2@futurewei.com>
v0.1, 2020-04-07
:toc: right

== Communication between ACA and OVS

TBD: XiaoDong to update the picture below, it will be good to add some text here also

                    +--------------------+
                    |  Alcor Control     |
                    |     Agent          |
                    +--------------------+
                    |  ovs-vsctl and     |
                    |   ofctl_api?       |
                    +--------------------+
         +--------------------------------------------------+
                    +--------------------+
                    |  ovs-db?           |
                    +--------------------+

== Highlevel Architecture

The Alcor Control Agent (ACA) running on the compute host provides the support of OVS dataplane programming through its dataplane abstraction layer interface. ACA will be configured to which dataplace to use (OVS - default or Mizar) during startup time and then execute the corresponding code through the dataplane abstraction layer.

Unlike openstack neutron which uses at least 5 RPC messages to simply configure a new port and have a notification to agent model from different sources. Alcor design should have only one message send from Alcor Controller to ACA, and that message would contain all the necessary network/port/security group/DHCP configuration to complete the configuration. The message can contain one or more (batching) configuration. ACA will parse the message and send the work item(s) to different ACA components for processing, with ability to execute multiple work items in parallel to greatly reduce the configuration time. Once all the work items are completed, it will provide the feedback to Alcor controller about success/fail status and elapse time stamps for record tracking. To summerize, we are looking at just one message send to ACA and one reply back to Alcor control to configure one or 1000s of new port(s).

TBD - Eric - to provide more design info

== OVS Implementation

TBD - Eric - what is OVS, why are we using it, what is the nice thing about OVS?


== Workflow with Alcor for port programming

TBD - Eric


== Programming OVS

TBD - XiaoDong

How do we call into OVS, what is the exact command we use to program a new port? What is the port configuration info needed?

A: we would use ovs-vsctl add-port cmd with lots of options to add or to configure (set port)

== OVS-db entries on Local Host

TBD - XiaoDong, I think it will be good to show how an entry looks like in ovs-db here

A: here is one example:
e72c1206-4e56-47fc-83b9-5c986af5ba8a
    Bridge "ovs0"
        Port "b8afb0bd725b4_l"
            tag: 100
            Interface "b8afb0bd725b4_l"
        Port "2fe20f38124d4_l"
            tag: 100
            Interface "2fe20f38124d4_l"
        Port "4a41eb1cac8c4_l"
            tag: 200
            Interface "4a41eb1cac8c4_l"
        Port "ovs0"
            Interface "ovs0"
                type: internal
        Port "vxlan1"
            Interface "vxlan1"
            options: {key=flow, remote_ip="x.x.x.x"}
         
            
== Alcor Network State Update

TBD - Eric - do we need to modify the current network state message? 


== Dataplane Programming Interface

TBD - Eric 


== OVS Implementation

TBD - XiaoDong

. when and who will initialize OVS? What are the initialization steps
.. br-int, br-tun are created during init time, and recreated later in RPC loop if needed
A: for the 1st questions:
.. there are several ways to init ovs, one is start openvswith service directly or we could do the following
a. start ovsdb-server, b. start vswitchd, use cmd to init as the following cmd:

a. ovsdb-server --remote=punix:/usr/local/var/run/openvswitch/db.sock  \
  --remote=db:Open_vSwitch,Open_vSwitch,manager_options \
  --private-key=db:Open_vSwitch,SSL,private_key  \
  --certificate=db:Open_vSwitch,SSL,certificate     \
  --bootstrap-ca-cert=db:Open_vSwitch,SSL,ca_cert  \
  --log-file=/var/log/openvswitch/ovs-vswitchd.log \
  -vsyslog:dbg -vfile:dbg  --pidfile --detach
 
b. ovs-vswitchd -v --pidfile --detach \
 --log-file=/var/log/openvswitch/ovs-vswitchd.log \
 -vconsole:err -vsyslog:info -vfile:info
c. ovs-vsctl --no-wait init

for the 2nd questions:
a. create bridge (adding internal port)
b. create tunnel to the bridge

. what happen when there are multiple physical NICs on the system, which NIC do we pick to hook up to br-tun, br-vlan, br-ex (if needed)? 
A:IMHO, during creation of ovs bridge there would be one virtual nic created with same name to the bridge , and if you run your compute instance inside container, there would be one more port on the host virtual nic which would be used as the hookup ( actually it's a pair veth device, one side conneted to vnic)
.. what is the exact command to connect the new port to the new br-tun, and enable encap/decap?
A:when you say port, i would assume you mean port in ovs instead of the OS socket port. In that case, if you only connect the port to the bridge , in ovs-vsctl cmd, it would be ovs-vsctl add-port bridgeName (br-tun name) portName

== Compare to Neutron Implementation

TBD. How is the perf, latency and availablity etc compare to Neutron?

== Outstanding Items:

. what happen if host crashed, do we save the OVS config locally and restore it? Or we ask the Alcor controller for the whole set of cofiguration upon restart


[bibliography]
== References

- [[[ovs,1]]] http://www.thekelleys.org.uk/dnsmasq/doc.html - need a OVS reference
